## Introduction
Link to competition: [Sentiment Analysis on Movie Reviews](https://www.kaggle.com/c/sentiment-analysis-on-movie-reviews/data)

My Kaggle Profile: [Amit Vikram | Kaggle](https://www.kaggle.com/amitkvikram)

### Import Data

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
Train = pd.read_csv("train.tsv", delimiter = '\t')
Test = pd.read_csv("test.tsv", delimiter = '\t')

In [13]:
Train.head(n=40)

,PhraseId,SentenceId,Phrase,Sentiment
0,1,1,A series of escapades demonstrating the adage ...,1
1,2,1,A series of escapades demonstrating the adage ...,2
2,3,1,A series,2
3,4,1,A,2
4,5,1,series,2
5,6,1,of escapades demonstrating the adage that what...,2
6,7,1,of,2
7,8,1,escapades demonstrating the adage that what is...,2
8,9,1,escapades,2
9,10,1,demonstrating the adage that what is good for ...,2
10,11,1,demonstrating the adage,2
11,12,1,demonstrating,2
12,13,1,the adage,2
13,14,1,the,2
14,15,1,adage,2
15,16,1,that what is good for the goose,2
16,17,1,that,2
17,18,1,what is good for the goose,2
18,19,1,what,2
19,20,1,is good for the goose,2
20,21,1,is,2
21,22,1,good for the goose,3
22,23,1,good,3
23,24,1,for the goose,2
24,25,1,for,2
25,26,1,the goose,2
26,27,1,goose,2
27,28,1,"is also good for the gander , some of which oc...",2
28,29,1,"is also good for the gander , some of which oc...",2
29,30,1,is also,2
30,31,1,also,2
31,32,1,"good for the gander , some of which occasional...",2
32,33,1,"for the gander , some of which occasionally am...",2
33,34,1,"the gander , some of which occasionally amuses...",1
34,35,1,"the gander ,",2
35,36,1,the gander,2
36,37,1,gander,2
37,38,1,",",2
38,39,1,some of which occasionally amuses but none of ...,2
39,40,1,some of which,2

In [11]:
Test.head()

   PhraseId  SentenceId                                             Phrase
0    156061        8545  An intermittently pleasing but mostly routine ...
1    156062        8545  An intermittently pleasing but mostly routine ...
2    156063        8545                                                 An
3    156064        8545  intermittently pleasing but mostly routine effort
4    156065        8545         intermittently pleasing but mostly routine